apiVersion: v1
kind: Secret
metadata:
  name: hfdigital-secret
  namespace: hfdigital
type: Opaque
stringData:
  APP_KEY: "base64:BBBh82fv5E7ceoAKj6X1h02mHBLFevVhLPNrwPZzy+E="
  DB_PASSWORD: "regis@2007"
