name: INTRODUCTION CI PIPELINE
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  runs-on: ubuntu-latest
  steps:
    build-and-review-code:
      uses: actions/checkout@v6
    - name: Verification du code
      uses: php-actions/php-cs-fixer@v3
        with:
          args: fix --dry-run --diff
      run: |
          composer install
          vendor/bin/php-cs-fixer fix --dry-run --diff
      
