name: HF Digital — CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests automatisés
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: hfdigital_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: regis@2007
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: pdo, pdo_pgsql
          coverage: none

      - name: Installer les dépendances PHP
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Installer les dépendances JS
        run: npm ci

      - name: Préparer le .env de test
        run: |
          cp .env.example .env
          php artisan key:generate

          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=hfdigital_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=regis@2007" >> .env
      - name: Attendre que PostgreSQL soit prêt
        run: |
          until pg_isready -h 127.0.0.1 -p 5432 -U postgres; do
            sleep 2
          done
      - name: Verifier les configurations de l'environnement
        run: grep DB_ .env
      - name: Lancer les migrations
        run: php artisan migrate --force
        

      # - name: Lancer les tests
      #   run: php artisan test
      - name: Finaliser le workflow
        run: echo "Workflow terminé avec succès !"
